namespace DataGenerator.Models;

/// <summary>
///	Which rows of a table are used: all of them, only the rows generated by the current run, or only the rows that
///	existed before it started.
/// </summary>
public enum RowScope
{
	Any       = 0,
	Generated = 1,
	Existing  = 2
}
