using System.Globalization;

namespace DataGenerator.Services.Patterns;

internal enum PatternArgumentKind
{
	Number     = 0,
	Range      = 1,
	Text       = 2,
	Expression = 3
}

internal sealed class PatternArgument
{
	private static readonly CultureInfo INVARIANT = CultureInfo.InvariantCulture;

	public required string?             Name        { get; init; }
	public required PatternArgumentKind Kind        { get; init; }
	public required string              Text        { get; init; }
	public required int                 Position    { get; init; }
	public decimal                      Number      { get; init; }
	public decimal                      RangeStart  { get; init; }
	public decimal                      RangeEnd    { get; init; }

	/// <summary>
	///	The nested function call of an <see cref="PatternArgumentKind.Expression"/> argument, e.g. TODAY() in RAND_DATE(TODAY(), '2030-12-31').
	/// </summary>
	public PatternNode?                 Expression  { get; init; }

	/// <summary>
	///	Whether the value was produced by a nested function call. Such a value is accepted wherever text is expected,
	///	even when it looks like a number (e.g. TODAY(format='yyyyMMdd')).
	/// </summary>
	public bool                         IsEvaluated { get; init; }

	/// <summary>
	///	Creates a copy of the argument using the text produced by its nested function call. Numeric text is kept as a number;
	///	all other text stays as text and is marked as evaluated.
	/// </summary>
	/// <param name="value">
	///	The value generated by the nested function call.
	/// </param>
	/// <returns>
	///	A copy of the argument whose value represents <paramref name="value"/>.
	/// </returns>
	public PatternArgument WithEvaluatedValue(string value)
	{
		bool isNumber = decimal.TryParse(
			value,
			NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint,
			INVARIANT,
			out decimal number
		);

		return new PatternArgument
		{
			Name        = Name,
			Kind        = isNumber ? PatternArgumentKind.Number : PatternArgumentKind.Text,
			Text        = value,
			Position    = Position,
			Number      = isNumber ? number : 0,
			IsEvaluated = true
		};
	}
}

/// <summary>
///	Binds positional and named function arguments (e.g. <c>SEQ(1-1000, start=5, digits=6)</c>) to parameters.
///	A range parameter accepts either a range (<c>1-1000</c>, <c>1..1000</c>, <c>1 TO 1000</c>) or two numbers (<c>1, 1000</c>).
/// </summary>
internal sealed class PatternArgumentBinder
{
	public const long MAXIMUM_MAGNITUDE = 1_000_000_000_000_000_000;

	private static readonly CultureInfo INVARIANT = CultureInfo.InvariantCulture;

	private readonly string                              _functionName;
	private readonly int                                 _position;
	private readonly List<PatternArgument>               _positional = [];
	private readonly Dictionary<string, PatternArgument> _named      = new(StringComparer.OrdinalIgnoreCase);
	private int                                          _nextPositional;

	/// <summary>
	///	Splits a function call's arguments into positional and named lookups and rejects positional values after named ones or
	///	duplicate names.
	/// </summary>
	/// <param name="functionName">
	///	The function name used in validation messages.
	/// </param>
	/// <param name="arguments">
	///	The parsed arguments supplied to the function call.
	/// </param>
	/// <param name="position">
	///	The one-based position of the function name in the pattern.
	/// </param>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when unnamed arguments follow named arguments, or when a name is given more than once.
	/// </exception>
	public PatternArgumentBinder(string functionName, IReadOnlyList<PatternArgument> arguments, int position)
	{
		_functionName = functionName;
		_position     = position;

		foreach (PatternArgument argument in arguments)
		{
			if (argument.Name is null)
			{
				if (_named.Count > 0)
				{
					throw new PatternSyntaxException(
						$"In {_functionName}(...), unnamed values must come before named values such as digits=4.",
						argument.Position
					);
				}

				_positional.Add(argument);
			}
			else if (!_named.TryAdd(argument.Name, argument))
			{
				throw new PatternSyntaxException($"'{argument.Name}' is given more than once in {_functionName}(...).", argument.Position);
			}
		}
	}

	/// <summary>
	///	Builds a syntax error at the function's position with the function name prefixed to the message.
	/// </summary>
	/// <param name="message">
	///	The function-specific validation message.
	/// </param>
	/// <returns>
	///	A syntax exception ready to throw.
	/// </returns>
	public PatternSyntaxException Error(string message) => new PatternSyntaxException($"{_functionName}: {message}", _position);

	/// <summary>
	///	Reads a required range from range=, min=/max=, one positional range, or two positional numbers.
	/// </summary>
	/// <param name="example">
	///	An example function call to include in error messages.
	/// </param>
	/// <returns>
	///	The inclusive minimum and maximum values of the range.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the range is missing, malformed or reversed.
	/// </exception>
	public (decimal Minimum, decimal Maximum) RequireRange(string example)
	{
		if (TryTakeNamed("range", out PatternArgument? namedRange))
		{
			return ToRange(namedRange, example);
		}

		if (_named.ContainsKey("min") || _named.ContainsKey("max"))
		{
			decimal minimum = RequireNamedNumber("min");
			decimal maximum = RequireNamedNumber("max");

			return ValidateRange(minimum, maximum);
		}

		PatternArgument first = TakePositional() ?? throw Error($"a range is required, e.g. {example}.");

		if (first.Kind == PatternArgumentKind.Range)
		{
			return ToRange(first, example);
		}

		if (first.Kind == PatternArgumentKind.Number && PeekPositional() is { Kind: PatternArgumentKind.Number } second)
		{
			_ = TakePositional();
			return ValidateRange(first.Number, second.Number);
		}

		throw new PatternSyntaxException($"{_functionName}: expected a range, e.g. {example}.", first.Position);
	}

	/// <summary>
	///	Reads a required length from length=, a positional number, a positional range, or two positional numbers.
	/// </summary>
	/// <param name="example">
	///	An example function call to include in error messages.
	/// </param>
	/// <returns>
	///	The inclusive minimum and maximum lengths. A single length is returned as both values.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the length is missing, is not numeric, or names a reversed range.
	/// </exception>
	public (decimal Minimum, decimal Maximum) RequireLength(string example)
	{
		PatternArgument? argument =
			TryTakeNamed("length", out PatternArgument? namedLength)
				? namedLength
				: TakePositional();

		if (argument is null)
		{
			throw Error($"a length is required, e.g. {example}.");
		}

		if (argument.Kind == PatternArgumentKind.Range)
		{
			return ToRange(argument, example);
		}

		if (argument.Kind != PatternArgumentKind.Number)
		{
			throw new PatternSyntaxException($"{_functionName}: expected a length, e.g. {example}.", argument.Position);
		}

		if (argument.Name is null && PeekPositional() is { Kind: PatternArgumentKind.Number } maximumLength)
		{
			_ = TakePositional();
			return ValidateRange(argument.Number, maximumLength.Number);
		}

		return (argument.Number, argument.Number);
	}

	/// <summary>
	///	Reads an optional numeric parameter, preferring the named value and otherwise taking the next positional value.
	/// </summary>
	/// <param name="parameterName">
	///	The parameter name to look for.
	/// </param>
	/// <returns>
	///	The numeric value, or <see langword="null"/> when the parameter was not supplied.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the supplied value is not a number.
	/// </exception>
	public decimal? OptionalNumber(string parameterName)
	{
		PatternArgument? argument =
			TryTakeNamed(parameterName, out PatternArgument? namedArgument)
				? namedArgument
				: TakePositional();

		if (argument is null)
		{
			return null;
		}

		return
			argument.Kind == PatternArgumentKind.Number
				? argument.Number
				: throw new PatternSyntaxException($"{_functionName}: {parameterName} must be a number.", argument.Position);
	}

	/// <summary>
	///	Reads an optional text parameter, accepting evaluated nested-function values as text even when they look numeric.
	/// </summary>
	/// <param name="parameterName">
	///	The parameter name to look for.
	/// </param>
	/// <returns>
	///	The text value, or <see langword="null"/> when the parameter was not supplied.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the supplied value is not text.
	/// </exception>
	public string? OptionalText(string parameterName)
	{
		PatternArgument? argument =
			TryTakeNamed(parameterName, out PatternArgument? namedArgument)
				? namedArgument
				: TakePositional();

		if (argument is null)
		{
			return null;
		}

		return
			argument.Kind == PatternArgumentKind.Text || argument.IsEvaluated
				? argument.Text
				: throw new PatternSyntaxException($"{_functionName}: {parameterName} must be text, e.g. '{argument.Text}'.", argument.Position);
	}

	/// <summary>
	///	Reads a required text parameter.
	/// </summary>
	/// <param name="parameterName">
	///	The parameter name to look for.
	/// </param>
	/// <param name="example">
	///	An example function call to include when the value is missing.
	/// </param>
	/// <returns>
	///	The supplied text value.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the value is missing or is not text.
	/// </exception>
	public string RequireText(string parameterName, string example)
		=> OptionalText(parameterName) ?? throw Error($"{parameterName} is required, e.g. {example}.");

	/// <summary>
	///	Reads an optional parameter that may be text or a number and returns it as text.
	/// </summary>
	/// <param name="parameterName">
	///	The parameter name to look for.
	/// </param>
	/// <returns>
	///	The value text, or <see langword="null"/> when the parameter was not supplied.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the supplied value is neither text nor a number.
	/// </exception>
	public string? OptionalValue(string parameterName)
	{
		PatternArgument? argument =
			TryTakeNamed(parameterName, out PatternArgument? namedArgument)
				? namedArgument
				: TakePositional();

		if (argument is null)
		{
			return null;
		}

		return
			argument.Kind is PatternArgumentKind.Text or PatternArgumentKind.Number
				? argument.Text
				: throw new PatternSyntaxException($"{_functionName}: {parameterName} must be text or a number.", argument.Position);
	}

	/// <summary>
	///	Reads a required parameter that may be text or a number and returns it as text.
	/// </summary>
	/// <param name="parameterName">
	///	The parameter name to look for.
	/// </param>
	/// <param name="example">
	///	An example function call to include when the value is missing.
	/// </param>
	/// <returns>
	///	The value text.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the value is missing or is neither text nor a number.
	/// </exception>
	public string RequireValue(string parameterName, string example)
		=> OptionalValue(parameterName) ?? throw Error($"{parameterName} is required, e.g. {example}.");

	/// <summary>
	///	Checks whether a range is given, either positionally or as range=, min= or max=.
	/// </summary>
	/// <returns>
	///	<see langword="true"/> when a range-like argument is still available; otherwise <see langword="false"/>.
	/// </returns>
	public bool HasRangeArgument()
		=> PeekPositional() is not null || _named.ContainsKey("range") || _named.ContainsKey("min") || _named.ContainsKey("max");

	/// <summary>
	///	Takes all positional arguments that have not yet been consumed.
	/// </summary>
	/// <returns>
	///	The remaining positional arguments, or an empty list when none remain.
	/// </returns>
	public IReadOnlyList<PatternArgument> TakeRemainingPositional()
	{
		List<PatternArgument> remaining = [.. _positional.Skip(_nextPositional)];

		_nextPositional = _positional.Count;
		return remaining;
	}

	/// <summary>
	///	Converts a decimal value to a whole number within the pattern language's supported magnitude.
	/// </summary>
	/// <param name="value">
	///	The value to convert.
	/// </param>
	/// <param name="description">
	///	The value description used in validation messages.
	/// </param>
	/// <returns>
	///	The value as a 64-bit whole number.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when <paramref name="value"/> has a fraction or is outside the supported range.
	/// </exception>
	public long ToWholeNumber(decimal value, string description)
	{
		if (value != decimal.Truncate(value))
		{
			throw Error($"{description} must be a whole number.");
		}

		if (Math.Abs(value) > MAXIMUM_MAGNITUDE)
		{
			throw Error($"{description} must be between -{MAXIMUM_MAGNITUDE.ToString("N0", INVARIANT)} and {MAXIMUM_MAGNITUDE.ToString("N0", INVARIANT)}.");
		}

		return (long)value;
	}

	/// <summary>
	///	Converts a decimal value to a whole-number count within an allowed range.
	/// </summary>
	/// <param name="value">
	///	The value to convert.
	/// </param>
	/// <param name="description">
	///	The value description used in validation messages.
	/// </param>
	/// <param name="minimum">
	///	The smallest allowed count.
	/// </param>
	/// <param name="maximum">
	///	The largest allowed count.
	/// </param>
	/// <returns>
	///	The value as an integer count.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when <paramref name="value"/> is fractional or outside the allowed range.
	/// </exception>
	public int ToCount(decimal value, string description, int minimum, int maximum)
	{
		if (value != decimal.Truncate(value) || value < minimum || value > maximum)
		{
			throw Error($"{description} must be a whole number from {minimum} to {maximum}.");
		}

		return (int)value;
	}

	/// <summary>
	///	Checks that every positional and named argument has been consumed by the function factory.
	/// </summary>
	/// <param name="parameterNames">
	///	The valid parameter names to show in error messages.
	/// </param>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when extra positional values remain or an unknown named parameter was supplied.
	/// </exception>
	public void EnsureComplete(params string[] parameterNames)
	{
		if (_nextPositional < _positional.Count)
		{
			throw new PatternSyntaxException(
				$"{_functionName} received too many values. Parameters: {string.Join(", ", parameterNames)}.",
				_positional[_nextPositional].Position
			);
		}

		foreach (PatternArgument argument in _named.Values)
		{
			throw new PatternSyntaxException(
				$"{_functionName} has no parameter named '{argument.Name}'. Parameters: {string.Join(", ", parameterNames)}.",
				argument.Position
			);
		}
	}

	/// <summary>
	///	Removes and returns a named argument if it has not already been consumed.
	/// </summary>
	/// <param name="parameterName">
	///	The argument name to take.
	/// </param>
	/// <param name="argument">
	///	The matching argument when one was found; otherwise <see langword="null"/>.
	/// </param>
	/// <returns>
	///	<see langword="true"/> when the named argument was found and removed; otherwise <see langword="false"/>.
	/// </returns>
	private bool TryTakeNamed(string parameterName, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out PatternArgument? argument)
		=> _named.Remove(parameterName, out argument);

	/// <summary>
	///	Reads the next positional argument without consuming it.
	/// </summary>
	/// <returns>
	///	The next positional argument, or <see langword="null"/> when none remain.
	/// </returns>
	private PatternArgument? PeekPositional()
		=> _nextPositional < _positional.Count ? _positional[_nextPositional] : null;

	/// <summary>
	///	Consumes the next positional argument.
	/// </summary>
	/// <returns>
	///	The consumed positional argument, or <see langword="null"/> when none remain.
	/// </returns>
	private PatternArgument? TakePositional()
	{
		PatternArgument? argument = PeekPositional();

		if (argument is not null)
		{
			++_nextPositional;
		}

		return argument;
	}

	/// <summary>
	///	Consumes a required named argument and verifies that it is numeric.
	/// </summary>
	/// <param name="parameterName">
	///	The name of the required argument.
	/// </param>
	/// <returns>
	///	The named argument's numeric value.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the argument is missing or is not a number.
	/// </exception>
	private decimal RequireNamedNumber(string parameterName)
	{
		if (!TryTakeNamed(parameterName, out PatternArgument? argument))
		{
			throw Error($"{parameterName} is required when min/max are used.");
		}

		return
			argument.Kind == PatternArgumentKind.Number
				? argument.Number
				: throw new PatternSyntaxException($"{_functionName}: {parameterName} must be a number.", argument.Position);
	}

	/// <summary>
	///	Converts a parsed range or single number argument to inclusive range bounds.
	/// </summary>
	/// <param name="argument">
	///	The argument to convert.
	/// </param>
	/// <param name="example">
	///	An example function call to include when the value is not a range.
	/// </param>
	/// <returns>
	///	The inclusive minimum and maximum values. A single number is returned as both values.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when the argument is not a range or number, or when the range is reversed.
	/// </exception>
	private (decimal Minimum, decimal Maximum) ToRange(PatternArgument argument, string example)
	{
		return argument.Kind switch
		{
			PatternArgumentKind.Range  => ValidateRange(argument.RangeStart, argument.RangeEnd),
			PatternArgumentKind.Number => (argument.Number, argument.Number),
			_                          => throw new PatternSyntaxException($"{_functionName}: expected a range, e.g. {example}.", argument.Position)
		};
	}

	/// <summary>
	///	Checks that a range is written from its smallest value to its largest value.
	/// </summary>
	/// <param name="minimum">
	///	The proposed inclusive minimum value.
	/// </param>
	/// <param name="maximum">
	///	The proposed inclusive maximum value.
	/// </param>
	/// <returns>
	///	The same <paramref name="minimum"/> and <paramref name="maximum"/> values when the range is valid.
	/// </returns>
	/// <exception cref="PatternSyntaxException">
	///	Thrown when <paramref name="minimum"/> is greater than <paramref name="maximum"/>.
	/// </exception>
	private (decimal Minimum, decimal Maximum) ValidateRange(decimal minimum, decimal maximum)
	{
		if (minimum > maximum)
		{
			throw Error(
				$"the range {minimum.ToString(INVARIANT)} to {maximum.ToString(INVARIANT)} is reversed. "
				+ $"Write the smaller value first, e.g. {maximum.ToString(INVARIANT)}-{minimum.ToString(INVARIANT)}."
			);
		}

		return (minimum, maximum);
	}
}