using System.Globalization;
using DataGenerator.Models;

namespace DataGenerator.Services;

public sealed class ColumnValueGenerator : IColumnValueGenerator
{
	private const int    RANDOM_TEXT_LENGTH       = 20;
	private const int    RANDOM_BINARY_LENGTH     = 16;
	private const int    UNLIMITED_TEXT_LENGTH    = 4000;
	private const int    MAXIMUM_INTEGER_DIGITS   = 6;
	private const int    MAXIMUM_RANDOM_DECIMALS  = 4;
	private const int    SECONDS_PER_DAY          = 86_400;
	private const string RANDOM_TEXT_CHARACTERS   = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

	private static readonly DateTime RANDOM_DATE_MINIMUM = new DateTime(2000, 1, 1);
	private static readonly DateTime RANDOM_DATE_MAXIMUM = new DateTime(2030, 12, 31, 23, 59, 59);

	private readonly ISqlValueConverter     _converter;
	private readonly IRegexValueGenerator   _regexGenerator;
	private readonly IPatternValueGenerator _patternGenerator;
	private readonly IColumnValueCaster     _caster;

	public ColumnValueGenerator(
		ISqlValueConverter     converter,
		IRegexValueGenerator   regexGenerator,
		IPatternValueGenerator patternGenerator,
		IColumnValueCaster     caster
	)
	{
		_converter        = converter ?? throw new ArgumentNullException(nameof(converter));
		_regexGenerator   = regexGenerator ?? throw new ArgumentNullException(nameof(regexGenerator));
		_patternGenerator = patternGenerator ?? throw new ArgumentNullException(nameof(patternGenerator));
		_caster           = caster ?? throw new ArgumentNullException(nameof(caster));
	}

	public bool CanGenerate(ValueGenerationMode mode)
		=> mode is ValueGenerationMode.Random
			or ValueGenerationMode.Fixed
			or ValueGenerationMode.Sequence
			or ValueGenerationMode.Regex
			or ValueGenerationMode.Pattern
			or ValueGenerationMode.CopyColumn
			or ValueGenerationMode.Null;

	public IReadOnlyList<string> GetReferencedColumns(ColumnRule rule)
	{
		ArgumentNullException.ThrowIfNull(rule);

		return rule.GenerationMode switch
		{
			ValueGenerationMode.CopyColumn => string.IsNullOrWhiteSpace(rule.SourceColumnName) ? [] : [rule.SourceColumnName.Trim()],
			ValueGenerationMode.Pattern    => _patternGenerator.GetColumnReferences(rule.PatternExpression),
			_                              => []
		};
	}

	public object? Generate(ColumnRule rule, long rowIndex, IRowValueLookup? rowValues = null)
	{
		ArgumentNullException.ThrowIfNull(rule);

		ColumnModel column = rule.Column;

		return rule.GenerationMode switch
		{
			ValueGenerationMode.Null     => column.IsNullable
				? null
				: throw new InvalidOperationException($"Column [{column.Name}] does not allow NULL values."),
			ValueGenerationMode.Fixed    => _converter.ConvertText(column, rule.FixedValue),
			ValueGenerationMode.Sequence => _converter.ConvertSequenceValue(column, rule.SequenceStart + (rule.SequenceStep * rowIndex)),
			ValueGenerationMode.Regex    => _converter.ConvertGeneratedText(
				column,
				_regexGenerator.Generate(rule.RegexPattern, _converter.GetMaximumTextLength(column) ?? UNLIMITED_TEXT_LENGTH)
			),
			ValueGenerationMode.Pattern    => GeneratePatternValue(rule, rowIndex, rowValues),
			ValueGenerationMode.CopyColumn => _caster.Cast(column, GetRowValues(rule, rowValues).GetValue(rule.SourceColumnName.Trim())),
			ValueGenerationMode.Random     => GenerateRandomValue(column),
			_                              => throw new InvalidOperationException(
				$"Values for [{column.Name}] in '{rule.GenerationMode}' mode are resolved while the data is generated."
			)
		};
	}

	public string DescribeRandomValues(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		string sqlType = NormalizeType(column);

		return _converter.GetCategory(column) switch
		{
			SqlTypeCategory.Integer     => DescribeRandomInteger(sqlType),
			SqlTypeCategory.Decimal     => $"Random number from 0 to {DescribeDecimalMaximum(column, sqlType)}",
			SqlTypeCategory.Boolean     => "Random 0 or 1",
			SqlTypeCategory.Text        => $"Random {GetRandomTextLength(column)} letters and digits",
			SqlTypeCategory.DateTime    => sqlType == "date"
				? "Random date between 2000 and 2030"
				: "Random date and time between 2000 and 2030",
			SqlTypeCategory.Time        => "Random time of day",
			SqlTypeCategory.Guid        => "New random GUID for every row",
			SqlTypeCategory.Binary      => $"Random {GetRandomBinaryLength(column)} bytes",
			SqlTypeCategory.RowVersion  => "Generated by SQL Server",
			_                           => $"Random values are not supported for {_converter.GetDisplayType(column)}"
		};
	}

	/// <remarks>
	/// Patterns that use other columns are converted leniently, because the other column's value may not suit this column's
	/// type (e.g. text copied into an int column keeps only its digits). Other patterns must produce a valid value.
	/// </remarks>
	private object? GeneratePatternValue(ColumnRule rule, long rowIndex, IRowValueLookup? rowValues)
	{
		if (_patternGenerator.GetColumnReferences(rule.PatternExpression).Count == 0)
		{
			return _converter.ConvertGeneratedText(rule.Column, _patternGenerator.Generate(rule.PatternExpression, rowIndex));
		}

		IRowValueLookup lookup = GetRowValues(rule, rowValues);
		string          text   = _patternGenerator.Generate(
			rule.PatternExpression,
			rowIndex,
			columnName => _caster.ToText(lookup.GetValue(columnName))
		);

		return _caster.Cast(rule.Column, text);
	}

	private static IRowValueLookup GetRowValues(ColumnRule rule, IRowValueLookup? rowValues)
		=> rowValues ?? throw new InvalidOperationException(
			$"Column [{rule.Column.Name}] uses the value of another column, which is only available while rows are generated."
		);

	private object GenerateRandomValue(ColumnModel column)
	{
		Random random  = Random.Shared;
		string sqlType = NormalizeType(column);

		switch (_converter.GetCategory(column))
		{
			case SqlTypeCategory.Integer:
				return GenerateRandomInteger(sqlType, random);

			case SqlTypeCategory.Decimal:
				return GenerateRandomDecimal(column, sqlType, random);

			case SqlTypeCategory.Boolean:
				return random.Next(2) == 1;

			case SqlTypeCategory.Text:
				return GenerateRandomText(GetRandomTextLength(column), random);

			case SqlTypeCategory.DateTime:
				return GenerateRandomDateTime(sqlType, random);

			case SqlTypeCategory.Time:
				return TimeSpan.FromSeconds(random.Next(0, SECONDS_PER_DAY));

			case SqlTypeCategory.Guid:
				return Guid.NewGuid();

			case SqlTypeCategory.Binary:
				byte[] bytes = new byte[GetRandomBinaryLength(column)];
				random.NextBytes(bytes);
				return bytes;

			case SqlTypeCategory.RowVersion:
				throw new InvalidOperationException("rowversion values are always generated by SQL Server.");

			default:
				throw new NotSupportedException(
					$"Random values are not supported for {_converter.GetDisplayType(column)} columns. Use Fixed value, Pattern or NULL instead."
				);
		}
	}

	/// <remarks>
	/// A switch statement keeps the CLR type of each column type; a switch expression would widen every value to long.
	/// </remarks>
	private static object GenerateRandomInteger(string sqlType, Random random)
	{
		switch (sqlType)
		{
			case "tinyint":
				return (byte)random.Next(0, byte.MaxValue + 1);

			case "smallint":
				return (short)random.Next(0, short.MaxValue + 1);

			case "int":
				return random.Next(1, 1_000_001);

			default:
				return random.NextInt64(1, 1_000_000_001);
		}
	}

	private static object GenerateRandomDecimal(ColumnModel column, string sqlType, Random random)
	{
		switch (sqlType)
		{
			case "money":
				return Math.Round((decimal)(random.NextDouble() * 100_000), 2);

			case "smallmoney":
				return Math.Round((decimal)(random.NextDouble() * 10_000), 2);

			case "float":
				return Math.Round(random.NextDouble() * 100_000, MAXIMUM_RANDOM_DECIMALS);

			case "real":
				return (float)Math.Round(random.NextDouble() * 100_000, 2);
		}

		(int integerDigits, int decimals) = GetRandomDecimalShape(column);

		long    integerPart    = integerDigits == 0 ? 0 : random.NextInt64(0, Pow10(integerDigits));
		long    fractionDigits = decimals == 0 ? 0 : random.NextInt64(0, Pow10(decimals));
		decimal fraction       = decimals == 0 ? 0 : fractionDigits / (decimal)Pow10(decimals);

		return integerPart + fraction;
	}

	private static string DescribeRandomInteger(string sqlType) => sqlType switch
	{
		"tinyint"  => "Random whole number from 0 to 255",
		"smallint" => "Random whole number from 0 to 32,767",
		"int"      => "Random whole number from 1 to 1,000,000",
		_          => "Random whole number from 1 to 1,000,000,000"
	};

	private static string DescribeDecimalMaximum(ColumnModel column, string sqlType)
	{
		switch (sqlType)
		{
			case "money":
			case "float":
			case "real":
				return "100,000";

			case "smallmoney":
				return "10,000";
		}

		(int integerDigits, int decimals) = GetRandomDecimalShape(column);

		decimal maximum = Pow10(integerDigits) - (decimals == 0 ? 1 : 1m / Pow10(decimals));

		return maximum.ToString(decimals == 0 ? "N0" : $"N{decimals}", CultureInfo.InvariantCulture);
	}

	private static (int IntegerDigits, int Decimals) GetRandomDecimalShape(ColumnModel column)
	{
		int precision = column.Precision ?? 18;
		int scale     = column.Scale ?? 0;

		return (Math.Min(precision - scale, MAXIMUM_INTEGER_DIGITS), Math.Min(scale, MAXIMUM_RANDOM_DECIMALS));
	}

	/// <remarks>
	/// A switch statement keeps DateTime values as DateTime; a switch expression would convert them all to DateTimeOffset with the local offset.
	/// </remarks>
	private static object GenerateRandomDateTime(string sqlType, Random random)
	{
		long     ticks = random.NextInt64(RANDOM_DATE_MINIMUM.Ticks, RANDOM_DATE_MAXIMUM.Ticks);
		DateTime value = new DateTime(ticks - (ticks % TimeSpan.TicksPerSecond));

		switch (sqlType)
		{
			case "date":
				return value.Date;

			case "smalldatetime":
				return new DateTime(value.Year, value.Month, value.Day, value.Hour, value.Minute, 0);

			case "datetimeoffset":
				return new DateTimeOffset(value, TimeSpan.Zero);

			default:
				return value;
		}
	}

	private static string GenerateRandomText(int length, Random random)
	{
		char[] characters = new char[length];

		for (int index = 0; index < characters.Length; ++index)
		{
			characters[index] = RANDOM_TEXT_CHARACTERS[random.Next(RANDOM_TEXT_CHARACTERS.Length)];
		}

		return new string(characters);
	}

	private int GetRandomTextLength(ColumnModel column)
		=> Math.Min(_converter.GetMaximumTextLength(column) ?? RANDOM_TEXT_LENGTH, RANDOM_TEXT_LENGTH);

	private static int GetRandomBinaryLength(ColumnModel column)
		=> column.MaximumLength is null or < 1 ? RANDOM_BINARY_LENGTH : Math.Min(column.MaximumLength.Value, RANDOM_BINARY_LENGTH);

	private static long Pow10(int exponent)
	{
		long value = 1;

		for (int index = 0; index < exponent; ++index)
		{
			value *= 10;
		}

		return value;
	}

	private static string NormalizeType(ColumnModel column) => column.SqlType.Trim().ToLowerInvariant();
}