using System.Data;
using System.Globalization;
using DataGenerator.Interfaces;
using DataGenerator.Models;

namespace DataGenerator.Services;

public sealed class SqlValueConverter : ISqlValueConverter
{
	#region FIELDS
	private const decimal MONEY_MAXIMUM       = 922337203685477.5807m;
	private const decimal SMALL_MONEY_MAXIMUM = 214748.3647m;
	private const int     MONEY_SCALE         = 4;
	private const int     DEFAULT_PRECISION   = 18;
	private const int     DEFAULT_TIME_SCALE  = 7;
	private const int     SYSNAME_LENGTH      = 128;
	private const double  REAL_MAXIMUM        = 3.40E+38;

	private static readonly CultureInfo INVARIANT;
	private static readonly DateTime    DATETIME_MINIMUM;
	private static readonly DateTime    SMALL_DATETIME_MINIMUM;
	private static readonly DateTime    SMALL_DATETIME_MAXIMUM;
	private static readonly string[]    TRUE_VALUES;
	private static readonly string[]    FALSE_VALUES;
	#endregion FIELDS

	#region CONSTRUCTOR
	/// <summary>
	///	Sets the default values of the static fields and properties of <see cref="SqlValueConverter"/>.
	/// </summary>
	static SqlValueConverter()
	{
		INVARIANT              = CultureInfo.InvariantCulture;
		DATETIME_MINIMUM       = new(1753, 1, 1);
		SMALL_DATETIME_MINIMUM = new(1900, 1, 1);
		SMALL_DATETIME_MAXIMUM = new(2079, 6, 6, 23, 59, 0);
		TRUE_VALUES            = ["1", "true", "yes", "y", "on"];
		FALSE_VALUES           = ["0", "false", "no", "n", "off"];
	}

	/// <summary>
	///	Creates a new <see cref="SqlValueConverter"/>.
	/// </summary>
	public SqlValueConverter()
	{
	}
	#endregion CONSTRUCTOR

	#region METHODS
	#region PUBLIC
	/// <summary>
	///	Classifies a SQL column type into the value category used by generators and editors.
	/// </summary>
	/// <param name="column">
	///	The column whose SQL type is classified.
	/// </param>
	/// <returns>
	///	The supported value category, or <see cref="SqlTypeCategory.Unsupported"/> when the type has no specialised handling.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public SqlTypeCategory GetCategory(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		return NormalizeType(column) switch
		{
			"bigint" or "int" or "smallint" or "tinyint"                                   => SqlTypeCategory.Integer,
			"decimal" or "numeric" or "money" or "smallmoney" or "float" or "real"         => SqlTypeCategory.Decimal,
			"bit"                                                                          => SqlTypeCategory.Boolean,
			"char" or "varchar" or "nchar" or "nvarchar" or "text" or "ntext" or "sysname" => SqlTypeCategory.Text,
			"date" or "datetime" or "datetime2" or "smalldatetime" or "datetimeoffset"     => SqlTypeCategory.DateTime,
			"time"                                                                         => SqlTypeCategory.Time,
			"uniqueidentifier"                                                             => SqlTypeCategory.Guid,
			"binary" or "varbinary" or "image"                                             => SqlTypeCategory.Binary,
			"timestamp" or "rowversion"                                                    => SqlTypeCategory.RowVersion,
			_                                                                              => SqlTypeCategory.Unsupported
		};
	}

	/// <summary>
	///	Converts user-entered text to the CLR value expected for a SQL column type.
	/// </summary>
	/// <param name="column">
	///	The column that will receive the value.
	/// </param>
	/// <param name="text">
	///	The text entered by the user.
	/// </param>
	/// <returns>
	///	The converted CLR value, or the original text for unsupported column types.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> or <paramref name="text"/> is <see langword="null"/>.
	/// </exception>
	/// <exception cref="FormatException">
	///	Thrown when the text cannot be parsed or does not fit the column format.
	/// </exception>
	/// <exception cref="InvalidOperationException">
	///	Thrown when the column type is generated by SQL Server and cannot accept user text.
	/// </exception>
	/// <exception cref="OverflowException">
	///	Thrown when the parsed value is outside the supported range of the column type.
	/// </exception>
	public object ConvertText(ColumnModel column, string text)
	{
		ArgumentNullException.ThrowIfNull(column);
		ArgumentNullException.ThrowIfNull(text);

		string sqlType     = NormalizeType(column);
		string trimmedText = text.Trim();

		switch (GetCategory(column))
		{
			case SqlTypeCategory.Integer:
			{
				if (!long.TryParse(trimmedText, NumberStyles.Integer, INVARIANT, out long integerValue))
				{
					throw new FormatException($"'{text}' is not a whole number. Enter {DescribeAcceptedInput(column)}.");
				}

				return ConvertIntegerValue(column, integerValue);
			}

			case SqlTypeCategory.Decimal:
			{
				if (sqlType is "float" or "real")
				{
					if (!double.TryParse(trimmedText, NumberStyles.Float | NumberStyles.AllowThousands, INVARIANT, out double doubleValue)
						|| double.IsNaN(doubleValue)
						|| double.IsInfinity(doubleValue))
					{
						throw new FormatException($"'{text}' is not a number. Enter {DescribeAcceptedInput(column)}.");
					}

					return ConvertFloatingValue(column, doubleValue);
				}

				if (!decimal.TryParse(trimmedText, NumberStyles.Number | NumberStyles.AllowExponent, INVARIANT, out decimal decimalValue))
				{
					throw new FormatException($"'{text}' is not a number. Enter {DescribeAcceptedInput(column)}.");
				}

				return ConvertDecimalValue(column, decimalValue);
			}

			case SqlTypeCategory.Boolean:
			{
				if (TRUE_VALUES.Contains(trimmedText, StringComparer.OrdinalIgnoreCase))
				{
					return true;
				}

				if (FALSE_VALUES.Contains(trimmedText, StringComparer.OrdinalIgnoreCase))
				{
					return false;
				}

				throw new FormatException($"'{text}' is not a bit value. Enter {DescribeAcceptedInput(column)}.");
			}

			case SqlTypeCategory.Text:
			{
				EnsureTextLength(column, text, $"The text is {text.Length} characters long");
				return text;
			}

			case SqlTypeCategory.DateTime:
			{
				return ConvertDateTimeText(column, text, trimmedText, sqlType);
			}

			case SqlTypeCategory.Time:
			{
				if (!TimeSpan.TryParse(trimmedText, INVARIANT, out TimeSpan timeValue)
					|| timeValue < TimeSpan.Zero
					|| timeValue >= TimeSpan.FromDays(1))
				{
					throw new FormatException($"'{text}' is not a valid time of day. Enter {DescribeAcceptedInput(column)}.");
				}

				return timeValue;
			}

			case SqlTypeCategory.Guid:
			{
				if (!Guid.TryParse(trimmedText, out Guid guidValue))
				{
					throw new FormatException($"'{text}' is not a valid GUID. Enter {DescribeAcceptedInput(column)}.");
				}

				return guidValue;
			}

			case SqlTypeCategory.Binary:
			{
				return ConvertHexText(column, text, trimmedText);
			}

			case SqlTypeCategory.RowVersion:
			{
				throw new InvalidOperationException("rowversion values are always generated by SQL Server.");
			}

			default:
			{
				return text;
			}
		}
	}

	/// <summary>
	///	Converts user-entered text without throwing validation errors to the caller.
	/// </summary>
	/// <param name="column">
	///	The column that will receive the value.
	/// </param>
	/// <param name="text">
	///	The text entered by the user.
	/// </param>
	/// <param name="value">
	///	The converted CLR value when conversion succeeds; otherwise <see langword="null"/>.
	/// </param>
	/// <param name="errorMessage">
	///	An empty string when conversion succeeds; otherwise the validation error message.
	/// </param>
	/// <returns>
	///	<see langword="true"/> when the text was converted; otherwise <see langword="false"/>.
	/// </returns>
	public bool TryConvertText(ColumnModel column, string text, out object? value, out string errorMessage)
	{
		try
		{
			value        = ConvertText(column, text);
			errorMessage = string.Empty;
			return true;
		}
		catch (Exception exception) when (exception is FormatException or OverflowException or InvalidOperationException or ArgumentException)
		{
			value        = null;
			errorMessage = exception.Message;
			return false;
		}
	}

	/// <summary>
	///	Converts a numeric sequence result to a value that fits the target column.
	/// </summary>
	/// <param name="column">
	///	The column that will receive the sequence value.
	/// </param>
	/// <param name="value">
	///	The numeric value produced by the sequence generator.
	/// </param>
	/// <returns>
	///	The converted integer, decimal or text value for the target column.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	/// <exception cref="FormatException">
	///	Thrown when the sequence value has a fractional part for an integer column or too many decimal places.
	/// </exception>
	/// <exception cref="InvalidOperationException">
	///	Thrown when sequences are not supported for the column category.
	/// </exception>
	/// <exception cref="OverflowException">
	///	Thrown when the sequence value is outside the supported range of the column type.
	/// </exception>
	public object ConvertSequenceValue(ColumnModel column, decimal value)
	{
		ArgumentNullException.ThrowIfNull(column);

		switch (GetCategory(column))
		{
			case SqlTypeCategory.Integer:
			{
				if (value != decimal.Truncate(value))
				{
					throw new FormatException(
						$"The sequence produced {value.ToString(INVARIANT)}, but {GetDisplayType(column)} only stores whole numbers. "
						+ "Use whole numbers for the start and step."
					);
				}

				if (value < long.MinValue || value > long.MaxValue)
				{
					throw new OverflowException($"The sequence value {value.ToString(INVARIANT)} is outside the range of {GetDisplayType(column)}.");
				}

				return ConvertIntegerValue(column, (long)value);
			}

			case SqlTypeCategory.Decimal:
			{
				return
					NormalizeType(column) is "float" or "real"
						? ConvertFloatingValue(column, (double)value)
						: ConvertDecimalValue(column, value);
			}

			case SqlTypeCategory.Text:
			{
				string text = value.ToString(INVARIANT);
				EnsureTextLength(column, text, $"The sequence value '{text}' is {text.Length} characters long");
				return text;
			}

			default:
			{
				throw new InvalidOperationException($"Sequences are not supported for {GetDisplayType(column)} columns.");
			}
		}
	}

	/// <summary>
	///	Converts text produced by a generator to a value that can be stored in the target column.
	/// </summary>
	/// <param name="column">
	///	The column that will receive the generated value.
	/// </param>
	/// <param name="text">
	///	The generated text.
	/// </param>
	/// <returns>
	///	The converted CLR value for the target column, or the text itself for text columns.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> or <paramref name="text"/> is <see langword="null"/>.
	/// </exception>
	/// <exception cref="FormatException">
	///	Thrown when the generated text cannot be stored in the target column.
	/// </exception>
	public object ConvertGeneratedText(ColumnModel column, string text)
	{
		ArgumentNullException.ThrowIfNull(column);
		ArgumentNullException.ThrowIfNull(text);

		if (GetCategory(column) == SqlTypeCategory.Text)
		{
			EnsureTextLength(column, text, $"The generated value '{text}' is {text.Length} characters long");
			return text;
		}

		try
		{
			return ConvertText(column, text);
		}
		catch (Exception exception) when (exception is FormatException or OverflowException)
		{
			throw new FormatException(
				$"The generated value '{text}' cannot be stored in column [{column.Name}] ({GetDisplayType(column)}). {exception.Message}",
				exception
			);
		}
	}

	/// <summary>
	///	Formats a converted value as a SQL literal suitable for an INSERT statement.
	/// </summary>
	/// <param name="column">
	///	The column whose SQL type controls text quoting and fragment conversion.
	/// </param>
	/// <param name="value">
	///	The value to write, or <see langword="null"/> for SQL NULL.
	/// </param>
	/// <returns>
	///	The SQL literal text for the value.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public string ToSqlLiteral(ColumnModel column, object? value)
	{
		ArgumentNullException.ThrowIfNull(column);

		return value switch
		{
			null or DBNull                => "NULL",
			SqlFragment fragment          => $"CONVERT({GetTypeDeclaration(column)}, {fragment.Sql})",
			bool booleanValue             => booleanValue ? "1" : "0",
			string text                   => QuoteText(column, text),
			DateTime dateTimeValue        => $"'{FormatDateTimeLiteral(column, dateTimeValue)}'",
			DateTimeOffset offsetValue    => $"'{offsetValue.ToString("yyyy-MM-ddTHH:mm:ss.fffffffzzz", INVARIANT)}'",
			TimeSpan timeValue            => $"'{timeValue.ToString(@"hh\:mm\:ss\.fffffff", INVARIANT)}'",
			Guid guidValue                => $"'{guidValue:D}'",
			byte[] bytes                  => $"0x{Convert.ToHexString(bytes)}",
			float singleValue             => singleValue.ToString("R", INVARIANT),
			double doubleValue            => doubleValue.ToString("R", INVARIANT),
			decimal decimalValue          => decimalValue.ToString(INVARIANT),
			IFormattable formattableValue => formattableValue.ToString(null, INVARIANT),
			_                             => QuoteText(column, value.ToString() ?? string.Empty)
		};
	}

	/// <summary>
	///	Formats a converted value for previewing in the user interface.
	/// </summary>
	/// <param name="column">
	///	The column whose type controls date display.
	/// </param>
	/// <param name="value">
	///	The value to display, or <see langword="null"/> for NULL.
	/// </param>
	/// <returns>
	///	The user-facing display text for the value.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public string FormatForDisplay(ColumnModel column, object? value)
	{
		ArgumentNullException.ThrowIfNull(column);

		return value switch
		{
			null or DBNull                => "NULL",
			SqlFragment                   => "(resolved by SQL Server)",
			bool booleanValue             => booleanValue ? "1" : "0",
			string text                   => text,
			DateTime dateTimeValue        =>
				NormalizeType(column) == "date"
					? dateTimeValue.ToString("yyyy-MM-dd", INVARIANT)
					: dateTimeValue.ToString("yyyy-MM-dd HH:mm:ss", INVARIANT),
			DateTimeOffset offsetValue    => offsetValue.ToString("yyyy-MM-dd HH:mm:ss zzz", INVARIANT),
			TimeSpan timeValue            => timeValue.ToString(@"hh\:mm\:ss", INVARIANT),
			Guid guidValue                => guidValue.ToString("D").ToUpperInvariant(),
			byte[] bytes                  => $"0x{Convert.ToHexString(bytes)}",
			IFormattable formattableValue => formattableValue.ToString(null, INVARIANT),
			_                             => value.ToString() ?? string.Empty
		};
	}

	/// <summary>
	///	Builds the SQL type declaration used when converting literal fragments for a column.
	/// </summary>
	/// <param name="column">
	///	The column whose SQL type is declared.
	/// </param>
	/// <returns>
	///	A concrete SQL type declaration, with legacy and rowversion types mapped to convertible declarations.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public string GetTypeDeclaration(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		return NormalizeType(column) switch
		{
			"text"                      => "varchar(max)",
			"ntext"                     => "nvarchar(max)",
			"image"                     => "varbinary(max)",
			"timestamp" or "rowversion" => "binary(8)",
			"sysname"                   => $"nvarchar({SYSNAME_LENGTH})",
			_                           => GetDisplayType(column)
		};
	}

	/// <summary>
	///	Builds the SQL type text shown to the user for a column.
	/// </summary>
	/// <param name="column">
	///	The column whose SQL type is displayed.
	/// </param>
	/// <returns>
	///	The type name with length, precision or scale when that information applies.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public string GetDisplayType(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		string sqlType = NormalizeType(column);

		return sqlType switch
		{
			"char" or "varchar" or "nchar" or "nvarchar" or "binary" or "varbinary" => $"{sqlType}({FormatLength(column.MaximumLength)})",
			"decimal" or "numeric"                                                  => $"{sqlType}({column.Precision ?? DEFAULT_PRECISION}, {column.Scale ?? 0})",
			"datetime2" or "time" or "datetimeoffset"                               => $"{sqlType}({column.Scale ?? DEFAULT_TIME_SCALE})",
			_                                                                       => sqlType
		};
	}

	/// <summary>
	///	Finds the maximum number of text characters accepted by a text column.
	/// </summary>
	/// <param name="column">
	///	The column whose text limit is requested.
	/// </param>
	/// <returns>
	///	The maximum character count for bounded text columns; otherwise <see langword="null"/>.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public int? GetMaximumTextLength(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		return NormalizeType(column) switch
		{
			"char" or "varchar" or "nchar" or "nvarchar" => column.MaximumLength is null or < 1 ? null : column.MaximumLength,
			"sysname"                                    => SYSNAME_LENGTH,
			_                                            => null
		};
	}

	/// <summary>
	///	Maps a column's SQL Server type name to the closest <see cref="SqlDbType"/> value.
	/// </summary>
	/// <param name="column">
	///	The column whose database parameter type is requested.
	/// </param>
	/// <returns>
	///	The matching <see cref="SqlDbType"/>, or <see cref="SqlDbType.NVarChar"/> for unknown types.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public SqlDbType GetSqlDbType(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		return NormalizeType(column) switch
		{
			"bigint"                    => SqlDbType.BigInt,
			"int"                       => SqlDbType.Int,
			"smallint"                  => SqlDbType.SmallInt,
			"tinyint"                   => SqlDbType.TinyInt,
			"bit"                       => SqlDbType.Bit,
			"decimal" or "numeric"      => SqlDbType.Decimal,
			"money"                     => SqlDbType.Money,
			"smallmoney"                => SqlDbType.SmallMoney,
			"float"                     => SqlDbType.Float,
			"real"                      => SqlDbType.Real,
			"date"                      => SqlDbType.Date,
			"datetime"                  => SqlDbType.DateTime,
			"datetime2"                 => SqlDbType.DateTime2,
			"smalldatetime"             => SqlDbType.SmallDateTime,
			"datetimeoffset"            => SqlDbType.DateTimeOffset,
			"time"                      => SqlDbType.Time,
			"char"                      => SqlDbType.Char,
			"varchar"                   => SqlDbType.VarChar,
			"nchar"                     => SqlDbType.NChar,
			"text"                      => SqlDbType.Text,
			"ntext"                     => SqlDbType.NText,
			"uniqueidentifier"          => SqlDbType.UniqueIdentifier,
			"binary"                    => SqlDbType.Binary,
			"varbinary"                 => SqlDbType.VarBinary,
			"image"                     => SqlDbType.Image,
			"xml"                       => SqlDbType.Xml,
			"timestamp" or "rowversion" => SqlDbType.Timestamp,
			"sql_variant"               => SqlDbType.Variant,
			_                           => SqlDbType.NVarChar
		};
	}

	/// <summary>
	///	Describes the text the user can enter for a column's SQL type.
	/// </summary>
	/// <param name="column">
	///	The column whose accepted input is described.
	/// </param>
	/// <returns>
	///	A concise user-facing description of valid input for the column.
	/// </returns>
	/// <exception cref="ArgumentNullException">
	///	Thrown when <paramref name="column"/> is <see langword="null"/>.
	/// </exception>
	public string DescribeAcceptedInput(ColumnModel column)
	{
		ArgumentNullException.ThrowIfNull(column);

		string sqlType = NormalizeType(column);

		switch (GetCategory(column))
		{
			case SqlTypeCategory.Integer:
			{
				(long minimum, long maximum) = GetIntegerRange(sqlType);
				return $"a whole number from {minimum.ToString("N0", INVARIANT)} to {maximum.ToString("N0", INVARIANT)}";
			}

			case SqlTypeCategory.Decimal:
			{
				return sqlType switch
				{
					"money"      => $"a number from -{MONEY_MAXIMUM.ToString(INVARIANT)} to {MONEY_MAXIMUM.ToString(INVARIANT)} with up to {MONEY_SCALE} decimal places",
					"smallmoney" => $"a number from -{SMALL_MONEY_MAXIMUM.ToString(INVARIANT)} to {SMALL_MONEY_MAXIMUM.ToString(INVARIANT)} with up to {MONEY_SCALE} decimal places",
					"float"      => "a number, e.g. 1234.5678",
					"real"       => "a number, e.g. 1234.56",
					_            => DescribeDecimal(column)
				};
			}

			case SqlTypeCategory.Boolean:
			{
				return "1 or 0 (true/false and yes/no are also accepted)";
			}

			case SqlTypeCategory.Text:
			{
				int? maximumLength = GetMaximumTextLength(column);
				return
					maximumLength.HasValue
						? $"text of at most {maximumLength.Value.ToString("N0", INVARIANT)} characters"
						: "any text";
			}

			case SqlTypeCategory.DateTime:
			{
				return sqlType switch
				{
					"date"           => "a date such as 2024-12-31",
					"datetime"       => "a date and time from 1753-01-01 to 9999-12-31, such as 2024-12-31 13:45:00",
					"smalldatetime"  => "a date and time from 1900-01-01 to 2079-06-06, such as 2024-12-31 13:45",
					"datetimeoffset" => "a date, time and offset such as 2024-12-31 13:45:00 +10:00",
					_                => "a date and time such as 2024-12-31 13:45:00"
				};
			}

			case SqlTypeCategory.Time:
			{
				return "a time of day such as 13:45:00";
			}

			case SqlTypeCategory.Guid:
			{
				return "a GUID such as 3F2504E0-4F89-11D3-9A0C-0305E82C3301";
			}

			case SqlTypeCategory.Binary:
			{
				int? maximumBytes = column.MaximumLength is null or < 1 ? null : column.MaximumLength;
				return
					maximumBytes.HasValue
						? $"hexadecimal bytes such as 0x1A2B (at most {maximumBytes.Value.ToString(INVARIANT)} bytes)"
						: "hexadecimal bytes such as 0x1A2B";
			}

			case SqlTypeCategory.RowVersion:
			{
				return "nothing - SQL Server generates rowversion values";
			}

			default:
			{
				return $"text that SQL Server can convert to {GetDisplayType(column)}";
			}
		}
	}
	#endregion PUBLIC

	#region PRIVATE
	/// <summary>
	///	Normalises a column type name for comparisons.
	/// </summary>
	/// <param name="column">
	///	The column whose SQL type is normalised.
	/// </param>
	/// <returns>
	///	The trimmed lower-case SQL type name.
	/// </returns>
	private static string NormalizeType(ColumnModel column) => column.SqlType.Trim().ToLowerInvariant();

	/// <summary>
	///	Formats a SQL length value for a type declaration.
	/// </summary>
	/// <param name="maximumLength">
	///	The maximum length from metadata, or <see langword="null"/> when unbounded.
	/// </param>
	/// <returns>
	///	The numeric length, or <c>max</c> when the length is unbounded or invalid.
	/// </returns>
	private static string FormatLength(int? maximumLength)
		=> maximumLength is null or < 1 ? "max" : maximumLength.Value.ToString(INVARIANT);

	/// <summary>
	///	Finds the inclusive range of a SQL integer type.
	/// </summary>
	/// <param name="sqlType">
	///	The normalised SQL integer type name.
	/// </param>
	/// <returns>
	///	The minimum and maximum values allowed by the type.
	/// </returns>
	private static (long Minimum, long Maximum) GetIntegerRange(string sqlType) => sqlType switch
	{
		"tinyint"  => (byte.MinValue, byte.MaxValue),
		"smallint" => (short.MinValue, short.MaxValue),
		"int"      => (int.MinValue, int.MaxValue),
		_          => (long.MinValue, long.MaxValue)
	};

	/// <summary>
	///	Quotes text as a SQL string literal, using Unicode syntax unless the column is non-Unicode text.
	/// </summary>
	/// <param name="column">
	///	The column whose SQL type controls the literal prefix.
	/// </param>
	/// <param name="text">
	///	The text to quote.
	/// </param>
	/// <returns>
	///	The quoted SQL literal with embedded apostrophes escaped.
	/// </returns>
	private static string QuoteText(ColumnModel column, string text)
	{
		string escapedText = text.Replace("'", "''");

		return
			NormalizeType(column) is "char" or "varchar" or "text"
				? $"'{escapedText}'"
				: $"N'{escapedText}'";
	}

	/// <summary>
	///	Formats a date or date-time value using the precision expected by the SQL column type.
	/// </summary>
	/// <param name="column">
	///	The column whose date type controls the format.
	/// </param>
	/// <param name="value">
	///	The value to format.
	/// </param>
	/// <returns>
	///	The invariant SQL date or date-time text without surrounding quotes.
	/// </returns>
	private static string FormatDateTimeLiteral(ColumnModel column, DateTime value) => NormalizeType(column) switch
	{
		"date"          => value.ToString("yyyy-MM-dd", INVARIANT),
		"datetime"      => value.ToString("yyyy-MM-ddTHH:mm:ss.fff", INVARIANT),
		"smalldatetime" => value.ToString("yyyy-MM-ddTHH:mm:ss", INVARIANT),
		_               => value.ToString("yyyy-MM-ddTHH:mm:ss.fffffff", INVARIANT)
	};

	/// <summary>
	///	Counts significant decimal places after trimming trailing zeroes.
	/// </summary>
	/// <param name="value">
	///	The decimal value to inspect.
	/// </param>
	/// <returns>
	///	The number of significant digits after the decimal point, or zero for whole numbers.
	/// </returns>
	private static int CountDecimalPlaces(decimal value)
	{
		string text         = value.ToString(INVARIANT);
		int    decimalIndex = text.IndexOf('.');

		return decimalIndex < 0 ? 0 : text.TrimEnd('0').Length - decimalIndex - 1;
	}

	/// <summary>
	///	Counts the digits before the decimal point in the absolute value.
	/// </summary>
	/// <param name="value">
	///	The decimal value to inspect.
	/// </param>
	/// <returns>
	///	The number of integer digits, or zero when the integer part is zero.
	/// </returns>
	private static int CountIntegerDigits(decimal value)
	{
		decimal integerPart = decimal.Truncate(Math.Abs(value));

		return integerPart == 0 ? 0 : integerPart.ToString(INVARIANT).Length;
	}

	/// <summary>
	///	Converts a whole number to the CLR integer type that matches the SQL column.
	/// </summary>
	/// <param name="column">
	///	The integer column that will receive the value.
	/// </param>
	/// <param name="value">
	///	The whole number to convert.
	/// </param>
	/// <returns>
	///	A byte, short, int or long value for the SQL integer type.
	/// </returns>
	/// <exception cref="OverflowException">
	///	Thrown when <paramref name="value"/> is outside the range of the SQL integer type.
	/// </exception>
	private object ConvertIntegerValue(ColumnModel column, long value)
	{
		string sqlType               = NormalizeType(column);
		(long minimum, long maximum) = GetIntegerRange(sqlType);

		if (value < minimum || value > maximum)
		{
			throw new OverflowException(
				$"{value.ToString("N0", INVARIANT)} is outside the range of {sqlType}. Enter {DescribeAcceptedInput(column)}."
			);
		}

		// A switch statement keeps the CLR type of each column type; a switch expression would widen every value back to long.
		switch (sqlType)
		{
			case "tinyint":
			{
				return (byte)value;
			}

			case "smallint":
			{
				return (short)value;
			}

			case "int":
			{
				return (int)value;
			}

			default:
			{
				return value;
			}
		}
	}

	/// <summary>
	///	Converts a floating-point number to double or single precision as required by the SQL column.
	/// </summary>
	/// <param name="column">
	///	The floating-point column that will receive the value.
	/// </param>
	/// <param name="value">
	///	The parsed floating-point value.
	/// </param>
	/// <returns>
	///	A double value for float columns, or a single value for real columns.
	/// </returns>
	/// <exception cref="OverflowException">
	///	Thrown when a real value is outside the supported range.
	/// </exception>
	private object ConvertFloatingValue(ColumnModel column, double value)
	{
		if (NormalizeType(column) != "real")
		{
			return value;
		}

		if (Math.Abs(value) > REAL_MAXIMUM)
		{
			throw new OverflowException($"{value.ToString(INVARIANT)} is outside the range of real.");
		}

		return (float)value;
	}

	/// <summary>
	///	Validates and returns a decimal value for a fixed-precision SQL column.
	/// </summary>
	/// <param name="column">
	///	The decimal, numeric, money or smallmoney column that will receive the value.
	/// </param>
	/// <param name="value">
	///	The parsed decimal value.
	/// </param>
	/// <returns>
	///	The original decimal value when it fits the column.
	/// </returns>
	/// <exception cref="FormatException">
	///	Thrown when the value has more decimal places than the column allows.
	/// </exception>
	/// <exception cref="OverflowException">
	///	Thrown when the value has too many integer digits or is outside the money range.
	/// </exception>
	private object ConvertDecimalValue(ColumnModel column, decimal value)
	{
		string sqlType       = NormalizeType(column);
		int    decimalPlaces = CountDecimalPlaces(value);

		if (sqlType is "money" or "smallmoney")
		{
			decimal maximum = sqlType == "money" ? MONEY_MAXIMUM : SMALL_MONEY_MAXIMUM;

			if (Math.Abs(value) > maximum)
			{
				throw new OverflowException($"{value.ToString(INVARIANT)} is outside the range of {sqlType}. Enter {DescribeAcceptedInput(column)}.");
			}

			if (decimalPlaces > MONEY_SCALE)
			{
				throw new FormatException($"{value.ToString(INVARIANT)} has more than {MONEY_SCALE} decimal places.");
			}

			return value;
		}

		int precision = column.Precision ?? DEFAULT_PRECISION;
		int scale     = column.Scale ?? 0;

		if (decimalPlaces > scale)
		{
			throw new FormatException(
				$"{value.ToString(INVARIANT)} has {decimalPlaces} decimal places, but {GetDisplayType(column)} allows {scale}. "
				+ $"Enter {DescribeAcceptedInput(column)}."
			);
		}

		int integerDigits = CountIntegerDigits(value);

		if (integerDigits > precision - scale)
		{
			throw new OverflowException(
				$"{value.ToString(INVARIANT)} has too many digits for {GetDisplayType(column)}. Enter {DescribeAcceptedInput(column)}."
			);
		}

		return value;
	}

	/// <summary>
	///	Describes the precision and scale accepted by a decimal or numeric column.
	/// </summary>
	/// <param name="column">
	///	The decimal or numeric column to describe.
	/// </param>
	/// <returns>
	///	A user-facing description of the number of allowed digits.
	/// </returns>
	private string DescribeDecimal(ColumnModel column)
	{
		int precision = column.Precision ?? DEFAULT_PRECISION;
		int scale     = column.Scale ?? 0;

		return
			scale == 0
				? $"a whole number with at most {precision} digits"
				: $"a number with at most {precision - scale} digits before and {scale} after the decimal point";
	}

	/// <summary>
	///	Converts text to a date, time or offset value and checks the range of SQL Server date types.
	/// </summary>
	/// <param name="column">
	///	The date or time column that will receive the value.
	/// </param>
	/// <param name="text">
	///	The original user-entered text for error messages.
	/// </param>
	/// <param name="trimmedText">
	///	The trimmed text to parse.
	/// </param>
	/// <param name="sqlType">
	///	The normalised SQL date or time type name.
	/// </param>
	/// <returns>
	///	A <see cref="DateTime"/> or <see cref="DateTimeOffset"/> value for the SQL type.
	/// </returns>
	/// <exception cref="FormatException">
	///	Thrown when the text is not a valid date or date-time value.
	/// </exception>
	/// <exception cref="OverflowException">
	///	Thrown when the value is outside the range of the SQL date type.
	/// </exception>
	private object ConvertDateTimeText(ColumnModel column, string text, string trimmedText, string sqlType)
	{
		if (sqlType == "datetimeoffset")
		{
			if (!DateTimeOffset.TryParse(trimmedText, INVARIANT, DateTimeStyles.AllowWhiteSpaces | DateTimeStyles.AssumeLocal, out DateTimeOffset offsetValue))
			{
				throw new FormatException($"'{text}' is not a valid date and time. Enter {DescribeAcceptedInput(column)}.");
			}

			return offsetValue;
		}

		if (!DateTime.TryParse(trimmedText, INVARIANT, DateTimeStyles.AllowWhiteSpaces, out DateTime dateTimeValue))
		{
			throw new FormatException($"'{text}' is not a valid date. Enter {DescribeAcceptedInput(column)}.");
		}

		DateTime minimum = sqlType switch
		{
			"datetime"      => DATETIME_MINIMUM,
			"smalldatetime" => SMALL_DATETIME_MINIMUM,
			_               => DateTime.MinValue
		};
		DateTime maximum = sqlType == "smalldatetime" ? SMALL_DATETIME_MAXIMUM : DateTime.MaxValue;

		if (dateTimeValue < minimum || dateTimeValue > maximum)
		{
			throw new OverflowException($"'{text}' is outside the range of {sqlType}. Enter {DescribeAcceptedInput(column)}.");
		}

		return sqlType == "date" ? dateTimeValue.Date : dateTimeValue;
	}

	/// <summary>
	///	Converts hexadecimal text to bytes and checks the maximum length of a binary column.
	/// </summary>
	/// <param name="column">
	///	The binary column that will receive the bytes.
	/// </param>
	/// <param name="text">
	///	The original user-entered text for error messages.
	/// </param>
	/// <param name="trimmedText">
	///	The trimmed hexadecimal text, with or without a leading <c>0x</c>.
	/// </param>
	/// <returns>
	///	The bytes represented by <paramref name="trimmedText"/>.
	/// </returns>
	/// <exception cref="FormatException">
	///	Thrown when the text is not hexadecimal or is too long for the column.
	/// </exception>
	private byte[] ConvertHexText(ColumnModel column, string text, string trimmedText)
	{
		string hexText =
			trimmedText.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
				? trimmedText[2..]
				: trimmedText;

		bool isHexadecimal = hexText.All(Uri.IsHexDigit);

		if (hexText.Length % 2 != 0 || !isHexadecimal)
		{
			throw new FormatException($"'{text}' is not valid hexadecimal. Enter {DescribeAcceptedInput(column)}.");
		}

		byte[] bytes = Convert.FromHexString(hexText);

		if (column.MaximumLength is > 0 && bytes.Length > column.MaximumLength.Value)
		{
			throw new FormatException(
				$"The value is {bytes.Length} bytes long, but {GetDisplayType(column)} allows at most {column.MaximumLength.Value}."
			);
		}

		return bytes;
	}

	/// <summary>
	///	Throws when text is longer than the target column allows.
	/// </summary>
	/// <param name="column">
	///	The text column that will receive the value.
	/// </param>
	/// <param name="text">
	///	The text whose length is checked.
	/// </param>
	/// <param name="problem">
	///	The start of the validation message describing the value being checked.
	/// </param>
	/// <exception cref="FormatException">
	///	Thrown when the text is longer than the maximum column length.
	/// </exception>
	private void EnsureTextLength(ColumnModel column, string text, string problem)
	{
		int? maximumLength = GetMaximumTextLength(column);

		if (maximumLength.HasValue && text.Length > maximumLength.Value)
		{
			throw new FormatException(
				$"{problem}, but column [{column.Name}] ({GetDisplayType(column)}) allows at most {maximumLength.Value}."
			);
		}
	}
	#endregion PRIVATE
	#endregion METHODS
}