using DataGenerator.Models;

namespace DataGenerator.Services.Generation;

/// <summary>
/// The values a "Value from table" rule can use, read from the source table right before the rows of its row set are
/// generated. UNIQUE lookups give every row a different value; other lookups pick a random value for every row.
/// </summary>
internal sealed class LookupPool
{
	private const int SCRIPT_CHOICE_RANGE = 1_000_000_000;

	private List<object?>? _values;

	public LookupPool(
		int          number,
		ColumnLookup lookup,
		ColumnModel  targetColumn,
		int          requiredCount,
		string       selectStatement,
		string       location,
		bool         usesScriptVariables
	)
	{
		Number              = number;
		Lookup              = lookup;
		TargetColumn        = targetColumn;
		RequiredCount       = requiredCount;
		SelectStatement     = selectStatement;
		Location            = location;
		UsesScriptVariables = usesScriptVariables;
	}

	public int          Number              { get; }
	public ColumnLookup Lookup              { get; }

	/// <summary>
	/// The column that receives the values; the values are converted to its type.
	/// </summary>
	public ColumnModel  TargetColumn        { get; }

	/// <summary>
	/// The number of values needed: one per row for UNIQUE lookups, otherwise one.
	/// </summary>
	public int          RequiredCount       { get; }

	/// <summary>
	/// Selects the values, already converted to the type of the target column, in random order.
	/// </summary>
	public string       SelectStatement     { get; }

	/// <summary>
	/// The table, row set and column that use the values, for error messages.
	/// </summary>
	public string       Location            { get; }

	public bool         UsesScriptVariables { get; }

	public string VariableName      => $"@dg_lookup_{Number}";
	public string CountVariableName => $"@dg_lookup_{Number}_count";

	public string DescribeShortage()
	{
		string filter = Lookup.FilterKind == LookupFilterKind.None ? string.Empty : " that match the WHERE filter";
		string scope  = Lookup.Scope switch
		{
			RowScope.Generated => " in rows generated by this run",
			RowScope.Existing  => " in rows that existed before this run",
			_                  => string.Empty
		};

		return Lookup.IsUnique
			? $"'Value from table' needs {RequiredCount:N0} different values of {Lookup.SourceDisplayName}{scope}{filter} "
				+ "that are not used in this column yet, but fewer were found. Generate fewer rows, remove UNIQUE, or loosen the filter."
			: $"No values of {Lookup.SourceDisplayName}{scope}{filter} were found for 'Value from table'. "
				+ "Generate rows for that table first (in an earlier step), or loosen the filter.";
	}

	public void Load(List<object?> values)
	{
		ArgumentNullException.ThrowIfNull(values);

		if (values.Count < RequiredCount)
		{
			throw new DataGenerationException(DescribeShortage(), Location);
		}

		_values = values;
	}

	/// <summary>
	/// The value for a row. In script mode the value is resolved by SQL Server from the table variable.
	/// </summary>
	public object? GetValue(long rowIndex, Random random)
	{
		if (UsesScriptVariables)
		{
			string rowNumber = Lookup.IsUnique
				? $"{rowIndex + 1}"
				: $"1 + ({random.Next(SCRIPT_CHOICE_RANGE)} % {CountVariableName})";

			return new SqlFragment(
				$"(SELECT {SqlSyntax.QuoteIdentifier(GeneratedKeyTable.GetValueColumnName(0))} FROM {VariableName} WHERE [RowNumber] = {rowNumber})"
			);
		}

		if (_values is null)
		{
			throw new InvalidOperationException($"The values of {Lookup.SourceDisplayName} have not been loaded.");
		}

		return Lookup.IsUnique ? _values[(int)rowIndex] : _values[random.Next(_values.Count)];
	}
}
