using DataGenerator.Models;

namespace DataGenerator.Services.Generation;

/// <summary>
///	A copy of some columns of a table, taken before any row is inserted, so rows can later be told apart as generated by
///	this run (not in the copy) or already existing (in the copy). Used by the "Generated rows" and "Existing rows" scopes.
/// </summary>
internal sealed class RowSnapshot
{
	#region FIELDS
	#region PRIVATE
	private const string ROW_ALIAS = "[b]";
	#endregion PRIVATE
	#endregion FIELDS

	#region PROPERTIES
	#region PUBLIC
	public int                   Number      { get; }
	public TableModel            Table       { get; }
	public IReadOnlyList<string> ColumnNames { get; }

	public string TableName => $"#dg_before_{Number}";
	#endregion PUBLIC
	#endregion PROPERTIES

	#region CONSTRUCTORS
	#region PUBLIC
	/// <summary>
	///	Creates a snapshot descriptor for one table and column set.
	/// </summary>
	/// <param name="number">
	///	Unique number used in the temporary table name.
	/// </param>
	/// <param name="table">
	///	The table whose existing rows are copied.
	/// </param>
	/// <param name="columnNames">
	///	The columns copied into the snapshot.
	/// </param>
	public RowSnapshot(int number, TableModel table, IReadOnlyList<string> columnNames)
	{
		Number      = number;
		Table       = table;
		ColumnNames = columnNames;
	}
	#endregion PUBLIC
	#endregion CONSTRUCTORS

	#region METHODS
	#region PUBLIC
	/// <summary>
	///	Builds the cache key for a table and snapshot column set.
	/// </summary>
	/// <param name="table">
	///	The table that will be snapshotted.
	/// </param>
	/// <param name="columnNames">
	///	The column names included in the snapshot.
	/// </param>
	/// <returns>
	///	A case-insensitive signature for reusing snapshots.
	/// </returns>
	public static string CreateSignature(TableModel table, IEnumerable<string> columnNames)
		=> $"{table.Key}|{string.Join("|", columnNames).ToUpperInvariant()}";

	/// <summary>
	///	Builds the SQL statement that removes this snapshot table if it exists.
	/// </summary>
	/// <returns>
	///	A DROP TABLE IF EXISTS statement for the snapshot table.
	/// </returns>
	public string BuildDropStatement() => $"DROP TABLE IF EXISTS {TableName};";

	/// <summary>
	///	Builds the SQL statement that copies the current distinct snapshot rows.
	/// </summary>
	/// <returns>
	///	A SELECT INTO statement that creates and fills the snapshot table.
	/// </returns>
	public string BuildCreateStatement()
	{
		string columns = string.Join(
			", ",
			ColumnNames
				.Select(
					(name, index) => $"{SqlSyntax.QuoteIdentifier(name)} AS {SqlSyntax.QuoteIdentifier(GeneratedKeyTable.GetValueColumnName(index))}"
				)
		);

		return $"SELECT DISTINCT {columns} INTO {TableName} FROM {Table.FullyQualifiedName};";
	}

	/// <summary>
	///	A condition on the row <paramref name="alias"/> (a row of <see cref="Table"/>) that is true when the row belongs to
	///	<paramref name="scope"/>; null for <see cref="RowScope.Any"/>.
	/// </summary>
	/// <param name="scope">
	///	The requested row scope.
	/// </param>
	/// <param name="alias">
	///	The SQL alias of the table row being tested.
	/// </param>
	/// <returns>
	///	A SQL condition for generated or existing rows, or <see langword="null"/> for any rows.
	/// </returns>
	public string? BuildScopeCondition(RowScope scope, string alias)
	{
		if (scope == RowScope.Any)
		{
			return null;
		}

		string matches = string.Join(
			" AND ",
			ColumnNames
				.Select(
					(name, index) => $"{ROW_ALIAS}.{SqlSyntax.QuoteIdentifier(GeneratedKeyTable.GetValueColumnName(index))} = {alias}.{SqlSyntax.QuoteIdentifier(name)}"
				)
		);
		string exists  = $"EXISTS (SELECT 1 FROM {TableName} AS {ROW_ALIAS} WHERE {matches})";

		return scope == RowScope.Existing ? exists : $"NOT {exists}";
	}
	#endregion PUBLIC
	#endregion METHODS
}

/// <summary>
///	The snapshots one run needs; every table and column combination is copied only once.
/// </summary>
internal sealed class RowSnapshotSet
{
	#region FIELDS
	#region PRIVATE
	private readonly Dictionary<string, RowSnapshot> _snapshots;
	private readonly List<RowSnapshot>               _ordered;
	#endregion PRIVATE
	#endregion FIELDS

	#region PROPERTIES
	#region PUBLIC
	public IReadOnlyList<RowSnapshot> Snapshots => _ordered;
	#endregion PUBLIC
	#endregion PROPERTIES

	#region CONSTRUCTORS
	#region PUBLIC
	/// <summary>
	///	Creates a new <see cref="RowSnapshotSet"/> and sets the default values of its fields and properties.
	/// </summary>
	public RowSnapshotSet()
	{
		_snapshots = new(StringComparer.OrdinalIgnoreCase);
		_ordered   = [];
	}
	#endregion PUBLIC
	#endregion CONSTRUCTORS

	#region METHODS
	#region PUBLIC
	/// <summary>
	///	Gets an existing snapshot descriptor or creates one for the table and columns.
	/// </summary>
	/// <param name="table">
	///	The table whose rows need to be snapshotted.
	/// </param>
	/// <param name="columnNames">
	///	The columns that identify rows for the requested scope.
	/// </param>
	/// <returns>
	///	The shared snapshot descriptor for the table and column set.
	/// </returns>
	public RowSnapshot Get(TableModel table, IReadOnlyList<string> columnNames)
	{
		string signature = RowSnapshot.CreateSignature(table, columnNames);

		if (!_snapshots.TryGetValue(signature, out RowSnapshot? snapshot))
		{
			snapshot = new RowSnapshot(_ordered.Count + 1, table, columnNames);
			_snapshots.Add(signature, snapshot);
			_ordered.Add(snapshot);
		}

		return snapshot;
	}
	#endregion PUBLIC
	#endregion METHODS
}
