using DataGenerator.Models;

namespace DataGenerator.Services.Generation;

/// <summary>
/// A copy of some columns of a table, taken before any row is inserted, so rows can later be told apart as generated by
/// this run (not in the copy) or already existing (in the copy). Used by the "Generated rows" and "Existing rows" scopes.
/// </summary>
internal sealed class RowSnapshot
{
	private const string ROW_ALIAS = "[b]";

	public RowSnapshot(int number, TableModel table, IReadOnlyList<string> columnNames)
	{
		Number      = number;
		Table       = table;
		ColumnNames = columnNames;
	}

	public int                   Number      { get; }
	public TableModel            Table       { get; }
	public IReadOnlyList<string> ColumnNames { get; }

	public string TableName => $"#dg_before_{Number}";

	public static string CreateSignature(TableModel table, IEnumerable<string> columnNames)
		=> $"{table.Key}|{string.Join("|", columnNames).ToUpperInvariant()}";

	public string BuildDropStatement() => $"DROP TABLE IF EXISTS {TableName};";

	public string BuildCreateStatement()
	{
		string columns = string.Join(
			", ",
			ColumnNames.Select((name, index) => $"{SqlSyntax.QuoteIdentifier(name)} AS {SqlSyntax.QuoteIdentifier(GeneratedKeyTable.GetValueColumnName(index))}")
		);

		return $"SELECT DISTINCT {columns} INTO {TableName} FROM {Table.FullyQualifiedName};";
	}

	/// <summary>
	/// A condition on the row <paramref name="alias"/> (a row of <see cref="Table"/>) that is true when the row belongs to
	/// <paramref name="scope"/>; null for <see cref="RowScope.Any"/>.
	/// </summary>
	public string? BuildScopeCondition(RowScope scope, string alias)
	{
		if (scope == RowScope.Any)
		{
			return null;
		}

		string matches = string.Join(
			" AND ",
			ColumnNames.Select(
				(name, index) => $"{ROW_ALIAS}.{SqlSyntax.QuoteIdentifier(GeneratedKeyTable.GetValueColumnName(index))} = {alias}.{SqlSyntax.QuoteIdentifier(name)}"
			)
		);
		string exists  = $"EXISTS (SELECT 1 FROM {TableName} AS {ROW_ALIAS} WHERE {matches})";

		return scope == RowScope.Existing ? exists : $"NOT {exists}";
	}
}

/// <summary>
/// The snapshots one run needs; every table and column combination is copied only once.
/// </summary>
internal sealed class RowSnapshotSet
{
	private readonly Dictionary<string, RowSnapshot> _snapshots = new(StringComparer.OrdinalIgnoreCase);
	private readonly List<RowSnapshot>               _ordered   = [];

	public IReadOnlyList<RowSnapshot> Snapshots => _ordered;

	public RowSnapshot Get(TableModel table, IReadOnlyList<string> columnNames)
	{
		string signature = RowSnapshot.CreateSignature(table, columnNames);

		if (!_snapshots.TryGetValue(signature, out RowSnapshot? snapshot))
		{
			snapshot = new RowSnapshot(_ordered.Count + 1, table, columnNames);
			_snapshots.Add(signature, snapshot);
			_ordered.Add(snapshot);
		}

		return snapshot;
	}
}
